name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: 
      image: composer:latest
    steps:
      - name: Run composer install
        run: composer install
        
