name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update system
      run: sudo apt update
      
    - name: Get wget
      run: sudo apt install wget unzip
      
    - name: Get Dependencies SDK 
      run: sudo apt install mono-complete dotnet-sdk-6.0
      
    - name: Get GDScript Only Repo Godot
      run: wget https://github.com/godotengine/godot/releases/download/4.1.1-stable/Godot_v4.1.1-stable_linux.x86_64.zip -O godot.zip
      
    - name: Unzip Godot
      run: unzip godot.zip
      
    - name: Moving Godot to binaries
      run: sudo mv Godot_v4.1.1-stable_linux.x86_64 /usr/local/bin/godot-engine
      
    - name: Give permission to Godot engine
      run: sudo chmod a+x /usr/local/bin/godot-engine
      
    - name: Launch Godot
      run: godot-engine
