name: Godot-Export-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: export game
      uses: firebelley/godot-export@v5.2.1
      with:
        godot_executable_download_url: http://downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_linux_x86_64.zip
        godot_export_templates_download_url: http://downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_export_templates.tpz
        relative_project_path: ./
        create_release: true
        run: godot -d -s --path "$PWD" addons/gut/gut_cmdln.gd
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
